companyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators= [DataRequired()])
    text = TextAreaField('Text', validators= [DataRequired()])
    submit=SubmitField("Post")

companyblog/blog_posts/views.py
from flask import render_template, request,url_for,flash,Blueprint, redirect, abort
from flask_login import current_user, login_required
from companyblog import db
from companyblog.models import BlogPost
from companyblog.blog_posts.forms import BlogPostForm

blog_posts=Blueprint('blog_posts',__name__)

#create
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form= BlogPostForm()

    if form.validate_on_submit():
        blog_post=BlogPost(title=form.title.data,
                            text=form.title.data,
                            user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)
# blog post
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post= BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                           date=blog_post.date,post=blog_post)

#update
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post= BlogPost.query.get_or_404(blog_post_id)
    
    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm() #fill the form
    if form.validate_on_submit():
        blog_post.title=form.title.data
        blog_post.text=form.text.data

        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id)) 
        #redirect to blog_post view

    elif request.method == 'GET':
        form.title.data=blog_post.title
        form.text.data=blog_post.text
    
    return render_template('create_post.html', title='Updating', form=form)

#delete
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete(blog_post_id):
    blog_post= BlogPost.query.get_or_404(blog_post_id)
     
    if blog_post.author != current_user:
        abort(403)  

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post delete')
    return redirect(url_for('core.index'))



        

    

companyblog/core/views.py
#home and infor view
from companyblog import BlogPost
from flask import render_template, request, Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_byorder_by(BlogPost.date.dec()).paginate(page=page,per_page=5)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

companyblog/users/views.py
from flask import render_template, request,url_for,flash,Blueprint, redirect
from flask_login import login_user, current_user, logout_user, login_required
from companyblog.models import User, BlogPost
from companyblog import db
from companyblog.users.forms import RegistrationForm,LoginForm,UpdateUserform
from companyblog.users.picture_handler import add_profile_pic

users= Blueprint('users',__name__)

#registration
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user =User(email=form.email.data,
                   username=form.username.data,
                   password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('thanks for registration')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

#login
@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('log in success!')

            next= request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
        return render_template('login.html',form=form)



#logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

# account
@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form=UpdateUserform()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic =add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username =form.username.data
        current_user.email= form.email.data

        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image= url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

# blog post
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.dec()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

companyblog/templates/account.html
{% extends "base.html" %}
{% block content %}

    <div class = "jumbotron">
        <div style= "align :center">
                <h1>Welcome to the page for {{current_user.username}}</h1>
                <img  style="align :center" src="{{url_for('static',filename='profile_pics/'+ current_user.profile_image)}}">

        
        </div>
    </div>

    <div class ="container">
    <form method="POST">
     {{form.hidden_tag()}}
        <div class = "form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
        </div>

        <div class = "form-group">
        {{form.email.label(class='form-group')}}
        {{form.email(class='form-control')}}
        </div>

        <div class = "form-group">
        {{form.picture.label(class='form-group')}}
        {{form.picture(class='form-control')}}
        </div>

        <div class = "form-group">
        {{form.submit(class='btn btn-primary')}}
        </div>



{% endblock %}

companyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>


</head>
<body>
    <ul class = 'nav'>
        <li class = 'nav-link'>
            <a href="{{url_for('core.index')}}">Home</a>

        </li>
        <li class = 'nav-link'>
            <a href="{{url_for('core.info')}}">about</a>


        {% if current_user.is_authenticated %}
        </li>
        <li class = 'nav-link'>
            <a href="{{url_for('users.logout')}}">log out</a>

        </li>
        <li class = 'nav-link'>
            <a href="{{url_for('users.account')}}">Account</a>

        </li>
        <li class = 'nav-link'>
            <a href="{{url_for('blog_posts.create_post')}}">Create Post</a>

        {% else %}

        </li>
        <li class = 'nav-link'>
            <a href="{{url_for('users.login')}}">log in</a>

        </li>
        <li class = 'nav-link'>
            <a href="{{url_for('users.register')}}">register</a>
        
        </li>
        {% endif %}
    </ul>
    <br>
    {% block content %}
    
    {% endblock %}

    
</body>
</html>

companyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{post.title}}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{post.date.strftime('%B %d, %Y')}}</h3>
  <p>{{post.text}}</p>

  {% if post.author == current_user %}
  <div>
    <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
    <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
  </div>

  {% endif %}
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{url_for('blog_posts.delete',blog_post_id=post.id)}}" method="post">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>


      </div>
    </div>
  </div>
</div>


{% endblock %}

companyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class ="container">
        <form class="form-group" method ="POST">
        {{form.hidden_tag()}}

        <div class="form-group" >'
        {{form.title.label(class='form-control-label')}}
        {{form.title(class='form-control form-control-lg')}}
        </div>

        <div class="form-group" >'
        {{form.text.label(class='form-control-label')}}
        {{form.text(class='form-control form-control-lg')}}
        </div>

        <div class="form-group" >'
        
        {{form.submit(class="btn btn-outline-info")}}
        </div>
        
        
    </div>

companyblog/templates/index.html
{% extends "base.html" %}
{% block content %}

    <div class = "jumbotron">
        <h1> Puppy company Blog </h1>
    </div>

    <div class= "container">
    {% for post in blog_posts.items %}

    {% endfor %}

{% endblock %}

companyblog/templates/info.html
{% extends "base.html" %}
{% block content %}

    <div class = "jumbotron">
        <h1>info about our company</h1>
        <p> A company is a legal entity formed by a group of individuals to engage in and operate a business—commercial or industrial—enterprise. A company may be organized in various ways for tax and financial liability purposes depending on the corporate law of its jurisdiction

        </p>
    </div>

{% endblock %}

companyblog/templates/login.html
{% extends "base.html" %}
{% block content %}

<form method ="POST">

{{form.hidden_tag()}}
{{form.email.label}}{{form.email}}<br>
{{form.password.label}}{{form.password}}<br>
{{form.submit()}}
</form>
{% endblock %}

companyblog/templates/register.html
{% extends "base.html" %}
{% block content %}

<form method ="POST">

{{form.hidden_tag()}}
{{form.email.label}}{{form.email}}<br>
{{form.username.label}}{{form.username}}<br>
{{form.password.label}}{{form.password}}<br>
{{form.pass_confirm.label}}{{form.pass_confirm}}<br>
{{form.submit()}}

</form>
{% endblock %}

companyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
    <div class ="container">
        <div class = "jumbotron">
            <h1>Welcome to the page for {{user.username}}</h1>
        <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
        </div>

        {% for post in blog_post.items %}
            <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a> </h2>
            written by: <a href ="{{url_for('users.user_post',username=post.author.username)}}"> {{post.author.username}}</a>
            <p class = 'text-muted'>Published on {{post.date.strftime("%y-%m-%d")}}</p>
            <br>
            <p>{{post.text}}</p>
            <br>
        {% endfor %}
    </div>

    <nav aria-label='Page Navigation example'>
        <ul class="pagination justify-content-center">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1,left_current=1,right_current=2) %}
            {% if blog_posts.page == page_num %}
            <li class='page-item disabled'>
                <a class = "page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a>
            </li>
            {% else %}
            <li clss="page-item">
            <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a>

            </li>
            {% endif %}
        {% endfor %}


        </ul>



{% endblock %}